In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
# default_exp mmult

# Matrix Multiply

Multiply 2 matrices

In [ ]:
#hide
from nbdev.showdoc import *

In [ ]:
import numpy as np

In [ ]:
#export
def dotp(v1, v2):
    "Get dot product of 2 vectors"
    sum = 0
    for i in range(0, len(v1)):
        sum += v1[i] * v2[i]
    return sum

In [ ]:
#export
def mmult(m1, m2):
    "Get product of 2 matrices using [dotp](/mmult#dotp) "
    import numpy as np
    assert m1.shape[1] == m2.shape[0]
    vsize = m1.shape[1]
    pmatrix = np.zeros((m1.shape[0],m2.shape[1]))
    for i in range(0,m1.shape[0]):
        for j in range(0,m2.shape[1]):
            nv = dotp(m1[i,:], m2[:,j])
            pmatrix[i,j] = nv
    return pmatrix

In [ ]:
m1 = np.random.rand(3,2)
m2 = np.random.rand(2,4)
m3 = mmult(m1, m2)
print(m1)
print(m2)
print(m3)

[[0.62355431 0.21682932]
 [0.70094478 0.9719229 ]
 [0.52716609 0.95615191]]
[[0.25789502 0.28198555 0.68997755 0.63448045]
 [0.52373966 0.51220411 0.84693224 0.96630073]]
[[0.27437366 0.28689417 0.61387822 0.60515535]
 [0.68980474 0.6954792  1.306789   1.38390557]
 [0.63672819 0.63839816 1.17352864 1.25840686]]
